In [2]:
import sys

In [3]:
sys.executable

'/Users/dennismacpro/miniconda3/bin/python'

In [4]:
sys.path

['/Users/dennismacpro/HelloML/MachineLearning/sample_project',
 '/Users/dennismacpro/miniconda3/lib/python37.zip',
 '/Users/dennismacpro/miniconda3/lib/python3.7',
 '/Users/dennismacpro/miniconda3/lib/python3.7/lib-dynload',
 '',
 '/Users/dennismacpro/miniconda3/lib/python3.7/site-packages',
 '/Users/dennismacpro/miniconda3/lib/python3.7/site-packages/IPython/extensions',
 '/Users/dennismacpro/.ipython']

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as ply
%matplotlib inline
from sklearn.datasets import load_boston
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

## 2.2 Choosing an estimator for a classification problem

In [11]:
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [12]:
len(heart_disease)

303

### Start with Linear SVC are class
https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html
SVC, NuSVC and LinearSVC are classes capable of performing multi-class classification on a dataset.

SVC and NuSVC are similar methods, but accept slightly different sets of parameters and have different mathematical formulations (see section Mathematical formulation). On the other hand, LinearSVC is another implementation of Support Vector Classification for the case of a linear kernel.

Consulting the map and it says to try `LinearSVC`

In [15]:
from sklearn.svm import LinearSVC

In [20]:
np.random.seed(42)

# Make the data
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   test_size=0.2)

# Instantiate LinearSVC
clf = LinearSVC(max_iter=10000)
clf.fit(X_train,y_train)

# Evaulate Linear SVC
clf.score(X_test, y_test)

/Users/dennismacpro/HelloML/MachineLearning/sample_project/env/lib/python3.8/site-packages/sklearn/svm/_base.py:946: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.47540983606557374

In [21]:
# below 0.5 is a trigger in our head
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

This a binary classsification, yet we are recieving a score under 50% only 47% accuracy, we are just guessing based on their attributes we woudl get 
50% so we are worse then random guessing
https://scikit-learn.org/stable/modules/ensemble.html


In [25]:
# import the RandomForestClassifier - known for robustness and ability
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)
clf = RandomForestClassifier(n_estimators=1000)
clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.8688524590163934

nice we are doiong much better now at 86% !
The goal of ensemble methods is to combine the predictions of several base estimators built with a given learning algorithm in order to improve generalizability / robustness over a single estimator.

table data such as data frames use ensemble methoods 

Tidbit:

    1. If you have structured data, use ensemble methods
    2. If you have unstructued data, use deep learning oor transfer learning (images, audio, text)
    
    
Get the data and figure out what problem you are truly trying to solv



## 3. Fit the model/algorithm and use it to make predictions on our data

###  3.1 Fitting thte model to the data

In [28]:
from sklearn.ensemble import RandomForestClassifier

# Setup a random seed
np.random.seed(42)

# make the data
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

#Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate Random Forest Classifer
clf = RandomForestClassifier()

# Fit the training data
clf.fit(X_train, y_train)

# Evaulate the test data (se the patterns the model formed)
clf.score(X_test, y_test)

0.8524590163934426

### 3.2 Make Predictions using a machine learning model

https://en.wikipedia.org/wiki/Random_forest
https://towardsdatascience.com/an-implementation-and-explanation-of-the-random-forest-in-python-77bf308a9b76
https://github.com/WillKoehrsen/Machine-Learning-Projects/blob/master/Random%20Forest%20Tutorial.ipynb
https://scikit-learn.org/stable/modules/tree.html
https://machinelearningmastery.com/classification-and-regression-trees-for-machine-learning/

Because a random forest in made of many decision trees, we’ll start by understanding how a single decision tree makes classifications on a simple problem.

A decision tree is the building block of a random forest and is an intuitive model. We can think of a decision tree as a series of yes/no questions asked about our data eventually leading to a predicted class (or continuous value in the case of regression).

All the nodes, except the leaf nodes (colored terminal nodes), have 5 parts:
Question asked about the data based on a value of a feature. Each question has either a True or False answer that splits the node. Based on the answer to the question, a data point moves down the tree.
gini: The Gini Impurity of the node. The average weighted Gini Impurity decreases as we move down the tree.
samples: The number of observations in the node.
value: The number of samples in each class. For example, the top node has 2 samples in class 0 and 4 samples in class 1.
class: The majority classification for points in the node. In the case of leaf nodes, this is the prediction for all samples in the node.

The leaf nodes do not have a question because these are where the final predictions are made. To classify a new point, simply move down the tree, using the features of the point to answer the questions until you arrive at a leaf node where the class is the prediction.

The random forest combines hundreds or thousands of decision trees, trains each one on a slightly different set of the observations, splitting nodes in each tree considering a limited number of the features. The final predictions of the random forest are made by averaging the predictions of each individual tree.


2 ways to make predictions

1. `predict()`
2. `predict_prooba()`

In [29]:
from sklearn.tree import export_graphviz

In [31]:
# use a trained model to make predictions
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [33]:
np.array([y_test])

array([[0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0]])

In [34]:
# Compare predictions to truth labels to evaulate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [35]:
clf.score(X_test, y_test)

0.8524590163934426

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.8524590163934426

#### Make predictions with predict_proba() 
#### predict_proba returns probablitiles of classification labels
https://github.com/scikit-learn/scikit-learn/blob/95d4f0841/sklearn/linear_model/_logistic.py#L1619

In [39]:
#predict_proba() returns probabilities of a classification label
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [40]:
# Let's predict() on the same data...
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [41]:
X_test[:5]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2